x-common: &common
  env_file:
    - .env
  logging:
    driver: "json-file"
    options:
      max-size: "100m"   # 100 МБ на файл
      max-file: "5"      # Хранить 10 файлов (1 ГБ всего)


services:
  umbrent-website:
    <<: *common
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - ${HTTPS_PORT}:${HTTPS_PORT}